import 'dart:io';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;
import 'package:vidra/features/settings/data/cookie_exporter.dart';
import 'package:vidra/features/settings/domain/netscape_cookie_formatter.dart';

void main() {
  group('CookieExporter', () {
    late Directory tempDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('vidra_cookie_test_');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('saves cookies to default webview_cookies.txt in baseDirectory', () async {
      final cookies = [
        Cookie(
          name: 'SID',
          value: 'sid_value_123',
          domain: 'youtube.com',
          path: '/',
          isSecure: true,
          expiresDate: 1780000000000,
        ),
      ];

      final expectedFilePath = p.join(tempDir.path, 'webview_cookies.txt');
      final returnedPath = await CookieExporter.saveCookiesToFile(
        cookies,
        savePath: expectedFilePath,
      );

      expect(returnedPath, equals(File(expectedFilePath).absolute.path));

      final file = File(returnedPath);
      expect(await file.exists(), isTrue);

      final content = await file.readAsString();
      final expectedContent = NetscapeCookieFormatter.format(cookies);
      expect(content, equals(expectedContent));
    });

    test('creates nested directory recursively when it does not exist', () async {
      final nestedDir = Directory(p.join(tempDir.path, 'nested', 'deep', 'dir'));
      final targetPath = p.join(nestedDir.path, 'custom_cookies.txt');

      final cookies = [
        Cookie(
          name: 'TOKEN',
          value: 'tok_abc',
          domain: 'example.com',
        ),
      ];

      final returnedPath = await CookieExporter.saveCookiesToFile(
        cookies,
        savePath: targetPath,
      );

      expect(returnedPath, equals(File(targetPath).absolute.path));
      expect(await File(targetPath).exists(), isTrue);
      expect(await nestedDir.exists(), isTrue);
    });

    test('overwrites existing cookie file on subsequent export', () async {
      final cookies1 = [
        Cookie(
          name: 'C1',
          value: 'V1',
          domain: 'site1.com',
        ),
      ];

      final cookies2 = [
        Cookie(
          name: 'C2',
          value: 'V2',
          domain: 'site2.com',
        ),
      ];

      final cookieFilePath = p.join(tempDir.path, 'webview_cookies.txt');

      final path1 = await CookieExporter.saveCookiesToFile(
        cookies1,
        savePath: cookieFilePath,
      );

      final content1 = await File(path1).readAsString();
      expect(content1, contains('site1.com'));
      expect(content1, isNot(contains('site2.com')));

      final path2 = await CookieExporter.saveCookiesToFile(
        cookies2,
        savePath: cookieFilePath,
      );

      expect(path1, equals(path2));

      final content2 = await File(path2).readAsString();
      expect(content2, contains('site2.com'));
      expect(content2, isNot(contains('site1.com')));
    });

    test('exports empty cookie list successfully with headers only', () async {
      final cookieFilePath = p.join(tempDir.path, 'webview_cookies.txt');
      final returnedPath = await CookieExporter.saveCookiesToFile(
        [],
        savePath: cookieFilePath,
      );

      final file = File(returnedPath);
      expect(await file.exists(), isTrue);

      final content = await file.readAsString();
      expect(
        content,
        equals(
          '# Netscape HTTP Cookie File\n'
          '# https://curl.haxx.se/rfc/cookie_spec.html\n'
          '# This file was generated by Vidra! Edit at your own risk.\n\n',
        ),
      );
    });

    group('sanitizeDomainFileName', () {
      test('sanitizes standard domains', () {
        expect(
          CookieExporter.sanitizeDomainFileName('youtube.com'),
          equals('youtube.com_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('.youtube.com'),
          equals('youtube.com_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('https://www.google.com/path'),
          equals('www.google.com_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('http://sub.domain.org:8080/foo'),
          equals('sub.domain.org_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('youtube.com/watch?v=123'),
          equals('youtube.com_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('m.tiktok.com/@creator/video/987'),
          equals('m.tiktok.com_cookies.txt'),
        );
      });

      test('sanitizes illegal file name characters and empty inputs', () {
        expect(
          CookieExporter.sanitizeDomainFileName(''),
          equals('default_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('   '),
          equals('default_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('domain*bad?chars<>|'),
          equals('domain_bad_chars____cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('host:8080'),
          equals('host_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('https://example.com:8443/auth?user=1#hash'),
          equals('example.com_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('CON'),
          equals('con_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('aux'),
          equals('aux_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('NUL'),
          equals('nul_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('COM1'),
          equals('com1_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('../../etc/passwd'),
          equals('etc_passwd_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('xn--d1acj3b.ru'),
          equals('xn--d1acj3b.ru_cookies.txt'),
        );
        expect(
          CookieExporter.sanitizeDomainFileName('...'),
          equals('default_cookies.txt'),
        );
      });
    });

    group('saveDomainCookies', () {
      test('saves cookies per-domain into vidra_cookies directory', () async {
        final cookies = [
          Cookie(
            name: 'LOGIN_INFO',
            value: 'secret123',
            domain: 'instagram.com',
          ),
        ];

        final filePath = await CookieExporter.saveDomainCookies(
          cookies,
          domain: 'instagram.com',
          directory: tempDir,
        );

        expect(p.basename(filePath), equals('instagram.com_cookies.txt'));
        final savedFile = File(filePath);
        expect(await savedFile.exists(), isTrue);

        final content = await savedFile.readAsString();
        expect(content, contains('instagram.com'));
        expect(content, contains('LOGIN_INFO'));
      });
    });

    group('getSavedCookieFiles', () {
      test('returns saved .txt files sorted by last modified descending', () async {
        // Create multiple cookie files with slight delay
        final file1 = File(p.join(tempDir.path, 'a_cookies.txt'));
        await file1.writeAsString('cookie A');

        await Future.delayed(const Duration(milliseconds: 20));
        final file2 = File(p.join(tempDir.path, 'b_cookies.txt'));
        await file2.writeAsString('cookie B');

        // Create a non-txt file that should be ignored
        final fileIgnored = File(p.join(tempDir.path, 'ignored.dat'));
        await fileIgnored.writeAsString('ignored');

        final files = CookieExporter.getSavedCookieFiles(
          directory: tempDir,
        );

        expect(files.length, equals(2));
        expect(files.first.path, equals(file2.path));
        expect(files.last.path, equals(file1.path));
      });

      test('safely returns empty list for non-existent directory', () {
        final emptySubdir = Directory(p.join(tempDir.path, 'non_existent_dir'));
        final files = CookieExporter.getSavedCookieFiles(
          directory: emptySubdir,
        );
        expect(files, isEmpty);
      });
    });
  });
}
