import 'dart:io';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;
import 'package:vidra/features/settings/data/cookie_exporter.dart';
import 'package:vidra/features/settings/domain/netscape_cookie_formatter.dart';

void main() {
  group('CookieExporter', () {
    late Directory tempDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('vidra_cookie_test_');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('saves cookies to default webview_cookies.txt in baseDirectory', () async {
      final cookies = [
        Cookie(
          name: 'SID',
          value: 'sid_value_123',
          domain: 'youtube.com',
          path: '/',
          isSecure: true,
          expiresDate: 1780000000000,
        ),
      ];

      final returnedPath = await CookieExporter.saveCookiesToFile(
        cookies,
        defaultDomain: 'youtube.com',
        baseDirectory: tempDir,
      );

      final expectedFilePath = p.join(tempDir.path, 'webview_cookies.txt');
      expect(returnedPath, equals(File(expectedFilePath).absolute.path));

      final file = File(returnedPath);
      expect(await file.exists(), isTrue);

      final content = await file.readAsString();
      final expectedContent = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'youtube.com',
      );
      expect(content, equals(expectedContent));
    });

    test('creates nested directory recursively when it does not exist', () async {
      final nestedDir = Directory(p.join(tempDir.path, 'nested', 'deep', 'dir'));
      final targetPath = p.join(nestedDir.path, 'custom_cookies.txt');

      final cookies = [
        Cookie(
          name: 'TOKEN',
          value: 'tok_abc',
          domain: 'example.com',
        ),
      ];

      final returnedPath = await CookieExporter.saveCookiesToFile(
        cookies,
        defaultDomain: 'example.com',
        targetPath: targetPath,
      );

      expect(returnedPath, equals(File(targetPath).absolute.path));
      expect(await File(targetPath).exists(), isTrue);
      expect(await nestedDir.exists(), isTrue);
    });

    test('overwrites existing cookie file on subsequent export', () async {
      final cookies1 = [
        Cookie(
          name: 'C1',
          value: 'V1',
          domain: 'site1.com',
        ),
      ];

      final cookies2 = [
        Cookie(
          name: 'C2',
          value: 'V2',
          domain: 'site2.com',
        ),
      ];

      final path1 = await CookieExporter.saveCookiesToFile(
        cookies1,
        defaultDomain: 'site1.com',
        baseDirectory: tempDir,
      );

      final content1 = await File(path1).readAsString();
      expect(content1, contains('site1.com'));
      expect(content1, isNot(contains('site2.com')));

      final path2 = await CookieExporter.saveCookiesToFile(
        cookies2,
        defaultDomain: 'site2.com',
        baseDirectory: tempDir,
      );

      expect(path1, equals(path2));

      final content2 = await File(path2).readAsString();
      expect(content2, contains('site2.com'));
      expect(content2, isNot(contains('site1.com')));
    });

    test('exports empty cookie list successfully with headers only', () async {
      final returnedPath = await CookieExporter.saveCookiesToFile(
        [],
        defaultDomain: 'google.com',
        baseDirectory: tempDir,
      );

      final file = File(returnedPath);
      expect(await file.exists(), isTrue);

      final content = await file.readAsString();
      expect(
        content,
        equals(
          '# Netscape HTTP Cookie File\n'
          '# https://curl.se/docs/http-cookies.html\n'
          '# This file was generated by Vidra! Edit at your own risk.\n\n',
        ),
      );
    });
  });
}
