import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:vidra/features/settings/domain/netscape_cookie_formatter.dart';

void main() {
  group('NetscapeCookieFormatter', () {
    test('formats empty cookie list with standard Netscape header', () {
      final result = NetscapeCookieFormatter.format(
        [],
        defaultDomain: 'youtube.com',
      );

      expect(
        result,
        equals(
          '# Netscape HTTP Cookie File\n'
          '# https://curl.se/docs/http-cookies.html\n'
          '# This file was generated by Vidra! Edit at your own risk.\n\n',
        ),
      );
    });

    test('formats persistent cookie with 7 tab-separated columns', () {
      final cookies = [
        Cookie(
          name: 'SESSION_ID',
          value: 'abc123xyz',
          domain: 'youtube.com',
          path: '/feed',
          isSecure: true,
          expiresDate: 1780000000000, // Milliseconds (~2026)
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'youtube.com',
      );

      final lines = result.trim().split('\n');
      // Header has 3 comment lines + 1 empty line, so cookie line is index 4 (5th line)
      expect(lines.length, equals(5));
      final cookieLine = lines[4];

      final cols = cookieLine.split('\t');
      expect(cols.length, equals(7));
      expect(cols[0], equals('.youtube.com'));
      expect(cols[1], equals('TRUE'));
      expect(cols[2], equals('/feed'));
      expect(cols[3], equals('TRUE'));
      expect(cols[4], equals('1780000000'));
      expect(cols[5], equals('SESSION_ID'));
      expect(cols[6], equals('abc123xyz'));
    });

    test('formats session cookie with expiry 0 when expiresDate is null or <= 0', () {
      final cookies = [
        Cookie(
          name: 'session_cookie_null',
          value: 'val1',
          domain: '.google.com',
          path: '/',
          isSecure: false,
          expiresDate: null,
        ),
        Cookie(
          name: 'session_cookie_zero',
          value: 'val2',
          domain: '.google.com',
          path: '/',
          isSecure: false,
          expiresDate: 0,
        ),
        Cookie(
          name: 'session_cookie_neg',
          value: 'val3',
          domain: '.google.com',
          path: '/',
          isSecure: false,
          expiresDate: -1,
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'google.com',
      );

      final lines = result.trim().split('\n');
      expect(lines.length, equals(7)); // 4 header lines + 3 cookies

      for (int i = 4; i < 7; i++) {
        final cols = lines[i].split('\t');
        expect(cols.length, equals(7));
        expect(cols[3], equals('FALSE'));
        expect(cols[4], equals('0')); // 0 expiration for session cookies
      }
    });

    test('handles timestamp already in seconds (<= 100 billion)', () {
      final cookies = [
        Cookie(
          name: 'SEC_EXPIRY',
          value: 'val',
          domain: 'example.com',
          expiresDate: 1780000000, // Seconds
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'example.com',
      );

      final lines = result.trim().split('\n');
      final cols = lines.last.split('\t');
      expect(cols[4], equals('1780000000'));
    });

    test('prepends leading dot and sets TRUE for domain-level cookies', () {
      final cookies = [
        Cookie(
          name: 'c1',
          value: 'v1',
          domain: 'sub.example.com',
        ),
        Cookie(
          name: 'c2',
          value: 'v2',
          domain: '.sub.example.com',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'example.com',
      );

      final lines = result.trim().split('\n');
      final cols1 = lines[4].split('\t');
      final cols2 = lines[5].split('\t');

      expect(cols1[0], equals('.sub.example.com'));
      expect(cols1[1], equals('TRUE'));

      expect(cols2[0], equals('.sub.example.com'));
      expect(cols2[1], equals('TRUE'));
    });

    test('handles IP addresses and localhost without leading dot and with FALSE', () {
      final cookies = [
        Cookie(
          name: 'ip_cookie',
          value: 'v_ip',
          domain: '127.0.0.1',
        ),
        Cookie(
          name: 'local_cookie',
          value: 'v_local',
          domain: 'localhost',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'localhost',
      );

      final lines = result.trim().split('\n');
      final cols1 = lines[4].split('\t');
      final cols2 = lines[5].split('\t');

      expect(cols1[0], equals('127.0.0.1'));
      expect(cols1[1], equals('FALSE'));

      expect(cols2[0], equals('localhost'));
      expect(cols2[1], equals('FALSE'));
    });

    test('falls back to defaultDomain when cookie domain is null or empty', () {
      final cookies = [
        Cookie(
          name: 'fallback_c',
          value: 'val',
          domain: null,
        ),
        Cookie(
          name: 'fallback_empty',
          value: 'val',
          domain: '   ',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'fallback.org',
      );

      final lines = result.trim().split('\n');
      final cols1 = lines[4].split('\t');
      final cols2 = lines[5].split('\t');

      expect(cols1[0], equals('.fallback.org'));
      expect(cols2[0], equals('.fallback.org'));
    });

    test('defaults empty or null path to / and ensures leading slash', () {
      final cookies = [
        Cookie(
          name: 'null_path',
          value: 'val',
          domain: 'test.com',
          path: null,
        ),
        Cookie(
          name: 'empty_path',
          value: 'val',
          domain: 'test.com',
          path: '   ',
        ),
        Cookie(
          name: 'unslashed_path',
          value: 'val',
          domain: 'test.com',
          path: 'custom/api',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'https://test.com:8443/some/page?q=1',
      );

      final lines = result.trim().split('\n');
      final cols1 = lines[4].split('\t');
      final cols2 = lines[5].split('\t');
      final cols3 = lines[6].split('\t');

      expect(cols1[0], equals('.test.com'));
      expect(cols1[2], equals('/'));
      expect(cols2[2], equals('/'));
      expect(cols3[2], equals('/custom/api'));
    });

    test('sanitizes tab, carriage return, and newline characters from name and value', () {
      final cookies = [
        Cookie(
          name: 'bad\tname\r\n',
          value: 'bad\tvalue\r\nwith\tmultiple\tcolumns',
          domain: 'clean.com',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'clean.com',
      );

      final lines = result.trim().split('\n');
      final cols = lines[4].split('\t');

      expect(cols.length, equals(7));
      expect(cols[5], equals('badname'));
      expect(cols[6], equals('badvaluewithmultiplecolumns'));
    });

    test('skips cookies whose name becomes empty after sanitization', () {
      final cookies = [
        Cookie(
          name: '\t\r\n  ',
          value: 'some_value',
          domain: 'example.com',
        ),
        Cookie(
          name: 'valid_cookie',
          value: 'valid_val',
          domain: 'example.com',
        ),
      ];

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'example.com',
      );

      final lines = result.trim().split('\n');
      // Only 1 cookie line (index 4)
      expect(lines.length, equals(5));
      final cols = lines[4].split('\t');
      expect(cols[5], equals('valid_cookie'));
    });

    test('handles multiple mixed cookies maintaining TSV integrity', () {
      final cookies = List.generate(
        100,
        (i) => Cookie(
          name: 'cookie_$i',
          value: 'val_hash_$i;key=value&foo=bar',
          domain: i.isEven ? 'domain$i.com' : '.sub$i.domain.net',
          path: '/path/$i',
          isSecure: i % 3 == 0,
          expiresDate: i % 2 == 0 ? 1750000000000 + i * 1000 : null,
        ),
      );

      final result = NetscapeCookieFormatter.format(
        cookies,
        defaultDomain: 'default.com',
      );

      final lines = result.trim().split('\n');
      expect(lines.length, equals(104)); // 4 header lines + 100 cookies

      for (int i = 0; i < 100; i++) {
        final line = lines[4 + i];
        final cols = line.split('\t');
        expect(cols.length, equals(7));
        expect(cols[5], equals('cookie_$i'));
        expect(cols[6], equals('val_hash_$i;key=value&foo=bar'));
      }
    });
  });
}
