const Map<String, String> languageEndonyms = {
  'aa': 'Afaan Qafar',
  'ab': 'аҧсуа бызшәа',
  'ae': 'avesta',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'አማርኛ',
  'an': 'aragonés',
  'ar': 'العربية',
  'as': 'অসমীয়া',
  'av': 'авар мацӀ',
  'ay': 'aymar aru',
  'az': 'azərbaycan dili',
  'ba': 'башҡорт теле',
  'be': 'беларуская мова',
  'bg': 'български език',
  'bi': 'Bislama',
  'bm': 'bamanankan',
  'bn': 'বাংলা',
  'bo': 'བོད་ཡིག',
  'br': 'brezhoneg',
  'bs': 'bosanski jezik',
  'ca': 'català',
  'ce': 'нохчийн мотт',
  'ch': 'Chamoru',
  'co': 'corsu',
  'cr': 'ᓀᐦᐃᔭᐍᐏᐣ',
  'cs': 'čeština',
  'cu': 'ѩзыкъ словѣньскъ',
  'cv': 'чӑваш чӗлхи',
  'cy': 'Cymraeg',
  'da': 'dansk',
  'de': 'Deutsch',
  'dv': 'ދިވެހި',
  'dz': 'རྫོང་ཁ',
  'ee': 'Eʋegbe',
  'el': 'Ελληνικά',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Español',
  'et': 'eesti',
  'eu': 'euskara',
  'fa': 'فارسی',
  'ff': 'Fulfulde',
  'fi': 'suomi',
  'fj': 'vosa Vakaviti',
  'fo': 'føroyskt',
  'fr': 'français',
  'fy': 'Frysk',
  'ga': 'Gaeilge',
  'gd': 'Gàidhlig',
  'gl': 'galego',
  'gn': 'Avañe\'ẽ',
  'gu': 'ગુજરાતી',
  'gv': 'Gaelg',
  'ha': 'Hausa',
  'he': 'עברית',
  'hi': 'हिन्दी',
  'ho': 'Hiri Motu',
  'hr': 'hrvatski jezik',
  'ht': 'Kreyòl ayisyen',
  'hu': 'magyar',
  'hy': 'Հայերեն',
  'hz': 'Otjiherero',
  'ia': 'interlingua',
  'id': 'Bahasa Indonesia',
  'ie': 'Interlingue',
  'ig': 'Asụsụ Igbo',
  'ii': 'ꆈꌠ꒿ Nuosuhxop',
  'ik': 'Iñupiaq',
  'io': 'Ido',
  'is': 'Íslenska',
  'it': 'italiano',
  'iu': 'ᐃᓄᒃᑎᑐᑦ',
  'ja': '日本語',
  'jv': 'basa Jawa',
  'ka': 'ქართული',
  'kg': 'Kikongo',
  'ki': 'Gĩkũyũ',
  'kj': 'Kuanyama',
  'kk': 'қазақ тілі',
  'kl': 'kalaallisut',
  'km': 'ខ្មែរ',
  'kn': 'ಕನ್ನಡ',
  'ko': '한국어',
  'kr': 'Kanuri',
  'ks': 'कश्मीरी',
  'ku': 'Kurdî',
  'kv': 'коми кыв',
  'kw': 'Kernewek',
  'ky': 'Кыргызча',
  'la': 'latine',
  'lb': 'Lëtzebuergesch',
  'lg': 'Luganda',
  'li': 'Limburgs',
  'ln': 'Lingála',
  'lo': 'ພາສາລາວ',
  'lt': 'lietuvių kalba',
  'lu': 'Tshiluba',
  'lv': 'latviešu valoda',
  'mg': 'fiteny malagasy',
  'mh': 'Kajin M̧ajeļ',
  'mi': 'te reo Māori',
  'mk': 'македонски јазик',
  'ml': 'മലയാളം',
  'mn': 'Монгол хэл',
  'mr': 'मराठी',
  'ms': 'bahasa Melayu',
  'mt': 'Malti',
  'my': 'ဗမာစာ',
  'na': 'Dorerin Naoero',
  'nb': 'Norsk bokmål',
  'nd': 'isiNdebele',
  'ne': 'नेपाली',
  'ng': 'Owambo',
  'nl': 'Nederlands',
  'nn': 'Norsk nynorsk',
  'no': 'Norsk',
  'nr': 'isiNdebele',
  'nv': 'Diné bizaad',
  'ny': 'chiCheŵa',
  'oc': 'occitan',
  'oj': 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  'om': 'Afaan Oromoo',
  'or': 'ଓଡ଼ିଆ',
  'os': 'ирон æвзаг',
  'pa': 'ਪੰਜਾਬੀ',
  'pi': 'पालि',
  'pl': 'polski',
  'ps': 'پښتو',
  'pt': 'Português',
  'qu': 'Runa Simi',
  'rm': 'rumantsch grischun',
  'rn': 'Ikirundi',
  'ro': 'română',
  'ru': 'Русский',
  'rw': 'Ikinyarwanda',
  'sa': 'संस्कृतम्',
  'sc': 'sardu',
  'sd': 'सिन्धी',
  'se': 'Davvisámegiella',
  'sg': 'yângâ tî sängö',
  'si': 'සිංහල',
  'sk': 'slovenčina',
  'sl': 'slovenščina',
  'sm': 'gagana Samoa',
  'sn': 'chiShona',
  'so': 'Soomaaliga',
  'sq': 'shqip',
  'sr': 'српски језик',
  'ss': 'SiSwati',
  'st': 'Sesotho',
  'su': 'Basa Sunda',
  'sv': 'svenska',
  'sw': 'Kiswahili',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'tg': 'тоҷикӣ',
  'th': 'ไทย',
  'ti': 'ትግርኛ',
  'tk': 'Türkmençe',
  'tl': 'Wikang Tagalog',
  'tn': 'Setswana',
  'to': 'faka Tonga',
  'tr': 'Türkçe',
  'ts': 'Xitsonga',
  'tt': 'татар теле',
  'tw': 'Twi',
  'ty': 'Reo Tahiti',
  'ug': 'ئۇيغۇر تىلى',
  'uk': 'українська',
  'ur': 'اردو',
  'uz': 'Oʻzbek',
  've': 'Tshivenḓa',
  'vi': 'Tiếng Việt',
  'vo': 'Volapük',
  'wa': 'walon',
  'wo': 'Wollof',
  'xh': 'isiXhosa',
  'yi': 'ייִדיש',
  'yo': 'Yorùbá',
  'za': 'Saɯ cueŋƅ',
  'zh': '中文',
  'zu': 'isiZulu',
};

const List<String> languageOptions = [
  'aa',
  'ab',
  'ae',
  'af',
  'ak',
  'am',
  'an',
  'ar',
  'as',
  'av',
  'ay',
  'az',
  'ba',
  'be',
  'bg',
  'bi',
  'bm',
  'bn',
  'bo',
  'br',
  'bs',
  'ca',
  'ce',
  'ch',
  'co',
  'cr',
  'cs',
  'cu',
  'cv',
  'cy',
  'da',
  'de',
  'dv',
  'dz',
  'ee',
  'el',
  'en',
  'eo',
  'es',
  'et',
  'eu',
  'fa',
  'ff',
  'fi',
  'fj',
  'fo',
  'fr',
  'fy',
  'ga',
  'gd',
  'gl',
  'gn',
  'gu',
  'gv',
  'ha',
  'he',
  'hi',
  'ho',
  'hr',
  'ht',
  'hu',
  'hy',
  'hz',
  'ia',
  'id',
  'ie',
  'ig',
  'ii',
  'ik',
  'io',
  'is',
  'it',
  'iu',
  'ja',
  'jv',
  'ka',
  'kg',
  'ki',
  'kj',
  'kk',
  'kl',
  'km',
  'kn',
  'ko',
  'kr',
  'ks',
  'ku',
  'kv',
  'kw',
  'ky',
  'la',
  'lb',
  'lg',
  'li',
  'ln',
  'lo',
  'lt',
  'lu',
  'lv',
  'mg',
  'mh',
  'mi',
  'mk',
  'ml',
  'mn',
  'mr',
  'ms',
  'mt',
  'my',
  'na',
  'nb',
  'nd',
  'ne',
  'ng',
  'nl',
  'nn',
  'no',
  'nr',
  'nv',
  'ny',
  'oc',
  'oj',
  'om',
  'or',
  'os',
  'pa',
  'pi',
  'pl',
  'ps',
  'pt',
  'qu',
  'rm',
  'rn',
  'ro',
  'ru',
  'rw',
  'sa',
  'sc',
  'sd',
  'se',
  'sg',
  'si',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sq',
  'sr',
  'ss',
  'st',
  'su',
  'sv',
  'sw',
  'ta',
  'te',
  'tg',
  'th',
  'ti',
  'tk',
  'tl',
  'tn',
  'to',
  'tr',
  'ts',
  'tt',
  'tw',
  'ty',
  'ug',
  'uk',
  'ur',
  'uz',
  've',
  'vi',
  'vo',
  'wa',
  'wo',
  'xh',
  'yi',
  'yo',
  'za',
  'zh',
  'zu',
];
