import 'package:flutter_inappwebview/flutter_inappwebview.dart';

/// Formatter that converts a list of [Cookie] objects from `flutter_inappwebview`
/// into the standard 7-column Netscape HTTP Cookie file format.
///
/// Netscape Cookie File format specification:
/// 1. domain (String): Domain that created/can read the cookie. If subdomain-matching, starts with '.'.
/// 2. include_subdomains (String): "TRUE" or "FALSE".
/// 3. path (String): Path scope for the cookie, default is "/".
/// 4. is_secure (String): "TRUE" or "FALSE".
/// 5. expiration (int): Unix timestamp in seconds (integer). 0 for session cookies.
/// 6. name (String): Cookie name.
/// 7. value (String): Cookie value.
class NetscapeCookieFormatter {
  /// Formats [cookies] into the Netscape HTTP Cookie file format.
  ///
  /// [defaultDomain] is used as a fallback if a cookie has an empty or null domain.
  static String format(List<Cookie> cookies) {
    final buffer = StringBuffer();
    buffer.writeln('# Netscape HTTP Cookie File');
    buffer.writeln('# https://curl.haxx.se/rfc/cookie_spec.html');
    buffer.writeln(
      '# This file was generated by Vidra! Edit at your own risk.',
    );
    buffer.writeln();

    for (final cookie in cookies) {
      final rawName = cookie.name.trim();
      final sanitizedName = rawName.replaceAll(RegExp(r'[\t\r\n]'), '');
      if (sanitizedName.isEmpty) {
        continue;
      }

      final rawValue = cookie.value?.toString() ?? '';
      final sanitizedValue = rawValue.replaceAll(RegExp(r'[\t\r\n]'), '');

      if (cookie.domain == null || cookie.domain!.trim().isEmpty) {
        continue;
      }

      var domain = cookie.domain!.trim();

      if (domain.startsWith('http://') || domain.startsWith('https://')) {
        final uri = Uri.tryParse(domain);
        if (uri != null && uri.host.isNotEmpty) {
          domain = uri.host;
        }
      } else if (domain.contains('/')) {
        final uri = Uri.tryParse('https://$domain');
        if (uri != null && uri.host.isNotEmpty) {
          domain = uri.host;
        }
      }
      if (domain.contains(':') &&
          !domain.startsWith('[') &&
          !domain.contains('::')) {
        domain = domain.split(':').first;
      }

      final isIp = RegExp(r'^\d+\.\d+\.\d+\.\d+$').hasMatch(domain);
      final bool includeSubdomains;

      if (isIp) {
        includeSubdomains = false;
      } else if (domain.startsWith('.')) {
        includeSubdomains = true;
      } else if (domain.contains('.')) {
        includeSubdomains = true;
        domain = '.$domain';
      } else {
        includeSubdomains = false;
      }

      final String domainFlag = includeSubdomains ? 'TRUE' : 'FALSE';

      final String rawPath = cookie.path?.trim() ?? '';
      final String path = rawPath.isNotEmpty
          ? (rawPath.startsWith('/') ? rawPath : '/$rawPath')
          : '/';

      final String secure = (cookie.isSecure == true) ? 'TRUE' : 'FALSE';

      int expirySeconds = 0;
      if (cookie.expiresDate != null && cookie.expiresDate! > 0) {
        // If timestamp is in milliseconds (> 100 billion), convert to seconds
        if (cookie.expiresDate! > 100000000000) {
          expirySeconds = (cookie.expiresDate! / 1000).round();
        } else {
          expirySeconds = cookie.expiresDate!;
        }
      }

      buffer.writeln(
        '$domain\t$domainFlag\t$path\t$secure\t$expirySeconds\t$sanitizedName\t$sanitizedValue',
      );
    }

    return buffer.toString();
  }
}
