display_name: Vidra
package_name: vidra

maintainer:
  name: chomusuke.dev
  email: 7k9mc4urn@mozmail.com

priority: optional
section: x11
installed_size: 500
essential: false
icon: assets/icon/icon.png

keywords:
  - Vidra
  - yt-dlp
  - Download

generic_name: Video Downloader

categories:
  - Network
  - Utility

startup_notify: true
