display_name: Vidra
package_name: vidra

maintainer:
  name: chomusuke.dev
  email: 7k9mc4urn@mozmail.com

priority: optional
section: net
installed_size: 250000
essential: false
icon: assets/icon/icon.png

postinstall_scripts:
  - mkdir -p /etc/apt/keyrings
  - if wget --quiet --timeout=5 --tries=2 -O /etc/apt/keyrings/chomusuke.asc https://apt.chomusuke.dev/public.key; then echo "deb [signed-by=/etc/apt/keyrings/chomusuke.asc] https://apt.chomusuke.dev/ stable main" > /etc/apt/sources.list.d/chomusuke.list; else rm -f /etc/apt/keyrings/chomusuke.asc; fi || true

description: |
  Vidra is an advanced video and task manager for the Linux desktop.
  It combines a modern Flutter user interface with a robust Python backend 
  powered by yt-dlp, FFmpeg, and QuickJS to seamlessly download and process media.

keywords:
  - Vidra
  - yt-dlp
  - Download
  - Video
  - Media
  - Manager
  - Flutter

generic_name: Advanced Video Download Manager

categories:
  - Network
  - Utility
  - AudioVideo

startup_notify: true
metainfo: linux/packaging/dev.chomusuke.vidra.appdata.xml
