name: vidra
title: Vidra
adopt-info: vidra
summary: Desktop-grade video download manager
description: |
  Vidra is an advanced video download manager for desktop and mobile devices. 
  It combines a modern Flutter user interface with a powerful Python backend 
  (yt-dlp), integrated seamlessly as a background process.

contact: https://github.com/chomusuke-mk/vidra/issues
license: GPL-3.0-or-later
issues: https://github.com/chomusuke-mk/vidra/issues
source-code: https://github.com/chomusuke-mk/vidra
website: https://chomusuke.dev
donation:
  - https://patreon.com/chomusuke_dev
  - https://buymeacoffee.com/chomusuke
icon: assets/icon/icon512.png
type: app

grade: stable
confinement: strict
compression: xz
base: core24

apps:
  vidra:
    command: vidra
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - wayland
      - audio-playback
    environment:
      # Fix for some Flutter apps under strict confinement finding their own assets
      FLUTTER_ASSET_DIR: $SNAP/data/flutter_assets

parts:
  vidra:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-environment:
      - SERIOUS_PYTHON_SITE_PACKAGES: $CRAFT_PART_SRC/.serious_python/site-packages
      - SERIOUS_PYTHON_APP: $CRAFT_PART_SRC/.serious_python/app
    override-build: |
      # 0. Set dynamic version from pubspec.yaml
      VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1 | xargs)
      craftctl set version="$VERSION"

      # Build the Flutter app
      craftctl default

  ffmpeg-dependencies:
    plugin: nil
    stage-packages:
      - libbz2-1.0 # Para libbz2.so.1.0
      - libnuma1 # Para libnuma.so.1
      - libva-x11-2 # Para libva-x11.so.2
      - libgomp1 # Para libgomp.so.1
      - libva2 # Para libva.so.2
      - libdrm2 # Para libdrm.so.2
      - libx11-6 # Para libX11.so.6
      - libxext6 # Para libXext.so.6
      - libxfixes3 # Para libXfixes.so.3
      - libx11-xcb1 # Para libX11-xcb.so.1
      - libxcb1 # Para libxcb.so.1
      - libxcb-dri3-0 # Para libxcb-dri3.so.0
      - libxau6 # Para libXau.so.6
      - libxdmcp6 # Para libXdmcp.so.6
  dependencias-python-tk:
    plugin: nil
    stage-packages:
      - libtcl9.0 # Para libtcl9.0.so
      - libtk9.0 # Para libtcl9tk9.0.so
