name: WinGet Manual Releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versión a publicar en WinGet (ej. 4.2.1)"
        required: true
        type: string

jobs:
  publish-winget:
    name: Publish to WinGet
    runs-on: windows-latest
    steps:
      - name: Format Version
        id: format_version
        shell: bash
        run: |
          VERSION="${{ inputs.version }}"
          CLEAN_VERSION="${VERSION#v}"
          echo "version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Download wingetcreate
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/wingetcreate/latest" -OutFile "wingetcreate.exe"

      - name: Sync Fork with Upstream
        shell: pwsh
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          gh repo sync "${{ github.repository_owner }}/winget-pkgs" -b master

      - name: Update and Submit Manifest to WinGet
        shell: pwsh
        run: |
          .\wingetcreate.exe update Chomusuke.Vidra `
            --urls "https://github.com/${{ github.repository }}/releases/download/${{ steps.format_version.outputs.version }}/vidra-windows.exe|x64|machine" `
            --version "${{ steps.format_version.outputs.version }}" `
            --token "${{ secrets.WINGET_TOKEN }}" `
            --no-open `
            --submit
